alias kclip='pbpaste | kubectl apply -f -'
alias pr='~/github/abugov/env/pr.sh'
alias gp='~/github/abugov/env/gp.sh'
alias gs='git status'
alias gd='git diff'
alias gpm='git checkout master && git pull'
alias grepc='grep -i -C 20'